### ISSUE TITLE
gstatic.com被墙，fonts.gstatic.com没有被墙，如何使列表更加准确

### ISSUE THREAD

**Issue by somelee** [Loyalsoldier/cn-blocked-domain#10]
gstatic.com被墙，fonts.gstatic.com没有被墙，如何使列表更加准确。

使用geosite:greatfire黑名单代理，fonts.gstatic.com等，geosite:google@cn中的域名也会被代理。

请问，是需要设置多个分流规则去规避这个问题，还是greatfire的精确度可以再提高一点？

**Comment by Loyalsoldier** [comment]
Greatfire 检测的精度就这样。还是设置多个分流规则规避这个问题吧。
