### ISSUE TITLE
economist、wsj、路透，三个app无法代理

### ISSUE THREAD

**Issue by haomuch** [Loyalsoldier/cn-blocked-domain#9]
economist（2.9.1），wsj（4.28.2.1）两个app完全无法通过列表代理，个人抓包技术有限，也无法解析出这两个app的服务器地址；路透app部分文章内图片无法通过此列表加载；以上三个媒体官网都可以通过此列表访问，所以应该是app的服务器另有网址。

希望作者可以补充相应被屏蔽的服务器网址。

**Comment by Loyalsoldier** [comment]
本项目只收集 Greatfire Analyzer 检测到的在中国大陆被屏蔽的域名，所以可能并不完整。

建议试一试这个更完整的域名列表：https://github.com/Loyalsoldier/v2ray-rules-dat/blob/release/proxy-list.txt

**Comment by haomuch** [comment]
这个proxy-list怎么样在v2ray里使用呢？难道把所有域名加上domian：，全部写进proxy规则吗？

**Comment by Loyalsoldier** [comment]
下载 geosite.dat：https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geosite.dat

然后使用类别：`geosite:geolocation-!cn`

**Comment by haomuch** [comment]
我就是因为不想代理所有境外网站，才使用您这个增强版geosite文件，既然有专门适用于黑名单模式的geosite规则，还是尽量补足比较好吧

**Comment by Loyalsoldier** [comment]
黑名单模式，请使用项目 https://github.com/Loyalsoldier/v2ray-rules-dat 中的类别 `geosite:gfw` 和 `geosite:greatfire`，但有些域名即使没有被封，也是会访问不了的，所以建议使用白名单模式。

**Comment by haomuch** [comment]
之前用的就是gfw和greatfire规则，发现多个app服务器地址缺失，实测geosite:geolocation-!cn也没有覆盖economist app服务器地址，但是覆盖了wsj和路透的服务器。另外您所说的即使没有被封，直连也访问不了是什么原因呢？

**Comment by Loyalsoldier** [comment]
丢包、网络链路质量不佳等……

**Comment by haomuch** [comment]
通过v2rayNg的流量嗅探，已经把这三个app的服务器域名找出来啦！分别是：
"main-ecnpaper-economist.content.pugpig.com",
"bartender.mobile.dowjones.io",
"tmsnrt.rs"
烦请作者将其加入到下一版geosite:greatfire吧

**Comment by Loyalsoldier** [comment]
这几个域名都没被封，建议自行添加到自己的配置文件中。

**Comment by haomuch** [comment]
即使没有被封，但是可能也有DNS劫持或者其他被干扰的连接问题，这样的域名应该也可以加入gfw规则吧？
